#!/usr/bin/env python3
"""Little Chits build plan runner.

The plan lives in plan/tasks.json. Each task has a spec (plan/tasks/Txx-*.md) and
acceptance tests written *before* implementation (plan/acceptance/). A task can only
be ticked off when:

  1. its acceptance files are unchanged (sha256 locked in tasks.json),
  2. its acceptance tests pass,
  3. the whole regular suite (tests/) still passes and hasn't shrunk,
  4. every previously-done task's acceptance tests still pass (no regressions),
  5. the web app still builds + web acceptance tests pass (for tasks marked "web").

Usage:
  python scripts/plan.py status            # checklist
  python scripts/plan.py next [--id]       # the next task whose dependencies are done
  python scripts/plan.py prompt T03        # a ready-to-paste prompt for a coding agent
  python scripts/plan.py verify T03        # run every gate, exit 0 only if all pass
  python scripts/plan.py done T03 [--commit]   # verify, then tick it off (+ git commit)
  PLAN_AUTHOR=1 python scripts/plan.py lock    # (plan author only) re-hash acceptance files
  PLAN_AUTHOR=1 python scripts/plan.py freeze  # (plan author only) tag the plan as plan-lock; gates then compare against it
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLAN = ROOT / "plan"
TASKS = PLAN / "tasks.json"
PROGRESS = PLAN / "PROGRESS.md"
REPORTS = PLAN / "reports"
PY = sys.executable


def load() -> dict:
    return json.loads(TASKS.read_text())


def save(data: dict) -> None:
    TASKS.write_text(json.dumps(data, indent=2) + "\n")
    write_progress(data)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


FROZEN_REF = os.environ.get("PLAN_FROZEN_REF", "plan-lock")


def frozen_ok(rel: str) -> bool:
    """If the plan author has frozen the plan (git tag `plan-lock`), an acceptance file must match that tag
    byte for byte. The hashes in tasks.json live on the same branch the agent edits; the tag doesn't."""
    has = subprocess.run(["git", "rev-parse", "-q", "--verify", f"refs/tags/{FROZEN_REF}"], cwd=ROOT,
                         capture_output=True).returncode == 0
    if not has:
        return True
    r = subprocess.run(["git", "show", f"{FROZEN_REF}:{rel}"], cwd=ROOT, capture_output=True)
    return r.returncode == 0 and hashlib.sha256(r.stdout).hexdigest() == sha(ROOT / rel)


def by_id(data: dict, tid: str) -> dict:
    tid = tid.upper()
    for t in data["tasks"]:
        if t["id"] == tid:
            return t
    sys.exit(f"unknown task {tid}")


def ready(data: dict, t: dict) -> bool:
    done = {x["id"] for x in data["tasks"] if x["status"] == "done"}
    return t["status"] != "done" and all(d in done for d in t.get("depends", []))


def write_progress(data: dict) -> None:
    lines = ["# Build progress", "", "Generated by `scripts/plan.py` — do not edit by hand.", ""]
    phase = None
    n_done = sum(t["status"] == "done" for t in data["tasks"])
    lines.append(f"**{n_done}/{len(data['tasks'])} tasks done**")
    for t in data["tasks"]:
        if t["phase"] != phase:
            phase = t["phase"]
            lines += ["", f"## {phase}", ""]
        box = "x" if t["status"] == "done" else " "
        when = f" — done {t['done_at']}" if t.get("done_at") else ""
        manual = " · 🖐 needs a manual GPU check" if t.get("manual") else ""
        lines.append(f"- [{box}] **{t['id']}** [{t['title']}]({Path(t['spec']).relative_to('plan')}){when}{manual}")
    PROGRESS.write_text("\n".join(lines) + "\n")


def run(cmd: list[str] | str, cwd: Path = ROOT, env: dict | None = None) -> tuple[int, str]:
    shell = isinstance(cmd, str)
    p = subprocess.run(cmd, cwd=cwd, shell=shell, capture_output=True, text=True,
                       env={**os.environ, **(env or {})})
    return p.returncode, (p.stdout + p.stderr)


def py_acceptance(t: dict) -> list[str]:
    return [a for a in t.get("acceptance", []) if a.endswith(".py")]


def web_acceptance(t: dict) -> list[str]:
    return [a for a in t.get("acceptance", []) if a.endswith(".ts")]


def collected_tests(path: str) -> int:
    code, out = run([PY, "-m", "pytest", path, "--collect-only", "-q", "-p", "no:cacheprovider"])
    m = re.search(r"(\d+) tests? collected", out)
    return int(m.group(1)) if m else 0


def verify(data: dict, t: dict, verbose: bool = True) -> bool:
    log: list[str] = []
    ok = True

    def gate(name: str, passed: bool, detail: str = "") -> None:
        nonlocal ok
        ok = ok and passed
        mark = "PASS" if passed else "FAIL"
        log.append(f"[{mark}] {name}")
        if detail and not passed:
            log.append(detail.strip()[-6000:])
        if verbose:
            print(f"[{mark}] {name}", flush=True)
            if detail and not passed:
                print(detail.strip()[-6000:], flush=True)

    # 1. acceptance tests are untouched
    for a in t.get("acceptance", []):
        p = ROOT / a
        want = t.get("sha256", {}).get(a)
        gate(f"acceptance file unchanged: {a}", p.exists() and want == sha(p) and frozen_ok(a),
             "Acceptance tests are the contract. Restore them (git checkout -- plan/) and change the code instead.")
    # 2. acceptance tests pass
    env = {"PYTHONPATH": str(ROOT / "server") + os.pathsep + str(ROOT / "tests")}
    for a in py_acceptance(t):
        code, out = run([PY, "-m", "pytest", a, "-q", "-p", "no:cacheprovider", "-x"], env=env)
        gate(f"acceptance: {a}", code == 0, out)
    if t.get("web") or web_acceptance(t):
        code, out = run("npm run build --silent", cwd=ROOT / "web")
        gate("web builds (tsc + vite)", code == 0, out)
        for a in web_acceptance(t):
            code, out = run(f"npx vitest run --root .. --globals {a}", cwd=ROOT / "web")
            gate(f"web acceptance: {a}", code == 0, out)
    # 3. the regular suite still passes and didn't shrink
    code, out = run([PY, "-m", "pytest", "tests", "-q", "-p", "no:cacheprovider"], env=env)
    gate("regular test suite (tests/)", code == 0, out)
    n = collected_tests("tests")
    base = data.get("baseline_tests", 0)
    gate(f"test count not reduced ({n} >= {base})", n >= base, "Tests were deleted. Restore them.")
    # 4. no regressions in earlier tasks (their tests must be untouched too, not just passing)
    for other in data["tasks"]:
        if other["status"] == "done" and other["id"] != t["id"]:
            for a in other.get("acceptance", []):
                p = ROOT / a
                gate(f"regression: {other['id']} acceptance unchanged: {a}",
                     p.exists() and other.get("sha256", {}).get(a) == sha(p) and frozen_ok(a),
                     "An earlier task's acceptance test was modified. Restore it (git checkout plan-lock -- " + a + ").")
            for a in py_acceptance(other):
                code, out = run([PY, "-m", "pytest", a, "-q", "-p", "no:cacheprovider"], env=env)
                gate(f"regression: {other['id']} {a}", code == 0, out)
            for a in web_acceptance(other):
                code, out = run(f"npx vitest run --root .. --globals {a}", cwd=ROOT / "web")
                gate(f"regression: {other['id']} {a}", code == 0, out)
    REPORTS.mkdir(exist_ok=True)
    (REPORTS / f"{t['id']}.txt").write_text(
        f"{t['id']} {t['title']}\n{dt.datetime.now().isoformat(timespec='seconds')}\n"
        + ("ALL GATES PASSED\n" if ok else "SOME GATES FAILED\n") + "\n".join(log) + "\n")
    if verbose:
        print(("\n✅ " if ok else "\n❌ ") + f"{t['id']}: {'all gates passed' if ok else 'not done yet'}")
    return ok


RULES = """RULES (read carefully):
- Implement ONLY this task. Do not start other tasks.
- NEVER edit anything under plan/ (specs, acceptance tests, tasks.json) — they are the contract.
- Never delete or weaken existing tests in tests/. You may add tests.
- Keep the code style of the surrounding files. Small, focused changes.
- When you think you're done, run:  python scripts/plan.py verify {id}
  Read the FAIL output, fix the code, and repeat until every gate says PASS.
- If a gate needs a real GPU/model that isn't available, stop and report it; don't fake it."""


def prompt(t: dict) -> str:
    spec = (ROOT / t["spec"]).read_text()
    acc = "\n".join(f"- {a}" for a in t.get("acceptance", []))
    return (f"You are implementing task {t['id']} of the Little Chits build plan.\n\n"
            f"{spec}\n\nAcceptance tests that must pass (read them first, they define the exact interface):\n{acc}\n\n"
            + RULES.format(id=t["id"]) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("status")
    n = sub.add_parser("next")
    n.add_argument("--id", action="store_true", help="print only the task id (for scripts)")
    for c in ("prompt", "verify", "done", "reopen"):
        s = sub.add_parser(c)
        s.add_argument("task")
        if c == "done":
            s.add_argument("--commit", action="store_true")
    sub.add_parser("lock")
    sub.add_parser("freeze")
    args = ap.parse_args()
    data = load()

    if args.cmd == "status":
        write_progress(data)
        for t in data["tasks"]:
            flag = "✔" if t["status"] == "done" else ("→" if ready(data, t) else "·")
            print(f" {flag} {t['id']}  {t['title']}")
        return
    if args.cmd == "next":
        for t in data["tasks"]:
            if ready(data, t):
                print(t["id"] if args.id else prompt(t))
                return
        if not args.id:
            print("🎉 Every task is done.")
        sys.exit(1)
    if args.cmd == "lock":
        if os.environ.get("PLAN_AUTHOR") != "1":
            sys.exit("lock is for the plan author only (PLAN_AUTHOR=1). Implementing agents must never re-hash tests.")
        for t in data["tasks"]:
            t["sha256"] = {a: sha(ROOT / a) for a in t.get("acceptance", [])}
        data["baseline_tests"] = collected_tests("tests")
        save(data)
        print(f"locked {sum(len(t['sha256']) for t in data['tasks'])} acceptance files; baseline {data['baseline_tests']} tests")
        return
    if args.cmd == "freeze":
        if os.environ.get("PLAN_AUTHOR") != "1":
            sys.exit("freeze is for the plan author only (PLAN_AUTHOR=1).")
        subprocess.run(["git", "tag", "-f", FROZEN_REF, "HEAD"], cwd=ROOT, check=True)
        print(f"tagged HEAD as {FROZEN_REF}. Push it with: git push -f origin {FROZEN_REF}  "
              "(and protect the tag in GitHub: Settings → Rules → Tags)")
        return
    t = by_id(data, args.task)
    if args.cmd == "prompt":
        print(prompt(t))
    elif args.cmd == "verify":
        sys.exit(0 if verify(data, t) else 1)
    elif args.cmd == "reopen":
        t["status"] = "todo"
        t.pop("done_at", None)
        save(data)
    elif args.cmd == "done":
        if not ready(data, t) and t["status"] != "done":
            sys.exit(f"{t['id']} depends on {t.get('depends')} which aren't done yet")
        if not verify(data, t):
            sys.exit(1)
        t["status"] = "done"
        t["done_at"] = dt.date.today().isoformat()
        data["baseline_tests"] = max(data.get("baseline_tests", 0), collected_tests("tests"))
        save(data)
        print(f"✔ ticked off {t['id']}")
        if args.commit:
            run(["git", "add", "-A"])
            code, out = run(["git", "commit", "-q", "-m", f"plan: {t['id']} {t['title']}"])
            print(out.strip() or "committed")


if __name__ == "__main__":
    main()
